// sapper/src/components/WidgetCard.svelte
<script>
  import WidgetCardDescription from "./WidgetCardDescription.svelte";
  import WidgetCardTag from "./WidgetCardTag.svelte";
  import WidgetCardTitle from "./WidgetCardTitle.svelte";

  export let tags = [
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
  ];
  export let title = "title";
  export let description = "description";
</script>

<style>
  .card {
    width: 300px;
    min-height: 300px;
    border: 2px solid magenta;
  }
</style>

<div class="card">
  <WidgetCardTitle>{title}</WidgetCardTitle>
  <WidgetCardDescription>{description}</WidgetCardDescription>
  {#each tags as tag (tag)}
    <WidgetCardTag>{tag}</WidgetCardTag>
  {/each}
</div>

// next/components/WidgetCard.jsx
import WidgetCardDescription from "./WidgetCardDescription";
import WidgetCardTag from "./WidgetCardTag";
import WidgetCardTitle from "./WidgetCardTitle";

function WidgetCard({ title, description }) {
  const tags = [
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
  ];

  return <div className="card">
    <WidgetCardTitle>{title}</WidgetCardTitle>
    <WidgetCardDescription>{description}</WidgetCardDescription>
    {tags.map(tag => <WidgetCardTag key={tag}>{tag}</WidgetCardTag>)}
  </div>
}

export default WidgetCard;
